import { useState } from "react";
import Head from "next/head";

import { Header } from "@/components/header/Header";
import { Filters } from "@/components/filters/Filters";
import { Videos } from "@/components/videos/Videos";

import { videosData } from "@/data/videos";

export default function Home() {
  const [filters, setFilters] = useState({});
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container flex gap-8 min-h-screen">
        <Filters filters={filters} onChange={() => setFilters({})} />
        <Videos videos={videosData} />
      </main>
    </>
  );
}
